# Generated by Django 3.2.6 on 2024-04-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20240414_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('-created_at',), 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
